const eventActionTypes = {
	TOGGLE_CREATE_EVENT: 'TOGGLE_CREATE_EVENT',
	TOGGLE_UPDATE_EVENT: 'TOGGLE_UPDATE_EVENT',
	TOGGLE_DELETE_EVENT: 'TOGGLE_DELETE_EVENT',

	
	GET_EVENT_PENDING: 'GET_EVENT_PENDING',
	GET_EVENT_SUCCESS: 'GET_EVENT_SUCCESS',
	GET_EVENT_FAILED: 'GET_EVENT_FAILED',

	CREATE_EVENT_PENDING: 'CREATE_EVENT_PENDING',
	CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
	CREATE_EVENT_FAILED: 'CREATE_EVENT_FAILED',

	UPDATE_EVENT_PENDING: 'UPDATE_EVENT_PENDING',
	UPDATE_EVENT_SUCCESS: 'UPDATE_EVENT_SUCCESS',
	UPDATE_EVENT_FAILED: 'UPDATE_EVENT_FAILED',

	DELETE_EVENT_PENDING: 'DELETE_EVENT_PENDING',
	DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
	DELETE_EVENT_FAILED: 'DELETE_EVENT_FAILED'
};

export default eventActionTypes;