const userActionTypes = {
	SET_USER_PENDING: 'SET_USER_PENDING',
	SET_USER_SUCCESS: 'SET_USER_SUCCESS',
	SET_USER_FAILED: 'SET_USER_FAILED',

	GET_USER_PENDING: 'GET_USER_PENDING',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_FAILED: 'GET_USER_FAILED',


	LOGOUT_USER: 'LOGOUT_USER',

	TOGGLE_LOGOUT_HIDDEN: 'TOGGLE_LOGOUT_HIDDEN'
};

export default userActionTypes;