const noteActionTypes = {
	TOGGLE_ADD_NOTE: 'TOGGLE_ADD_NOTE',


	GET_NOTE_PENDING: 'GET_NOTE_PENDING',
	GET_NOTE_SUCCESS: 'GET_NOTE_SUCCESS',
	GET_NOTE_FAILED: 'GET_NOTE_FAILED',

	ADD_NOTE_PENDING: 'ADD_NOTE_PENDING',
	ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
	ADD_NOTE_FAILED: 'ADD_NOTE_FAILED',

};

export default noteActionTypes;